# SPDX-FileCopyrightText: Space Station 14 Contributors <https://spacestation14.com/about/about/>
#
# SPDX-License-Identifier: MIT

- type: localizedDataset
  id: NamesFirst
  values:
    prefix: names-first-dataset-
    count: 1395

- type: localizedDataset
  id: NamesLast
  values:
    prefix: names-last-dataset-
    count: 553
