# SPDX-FileCopyrightText: Space Station 14 Contributors <https://spacestation14.com/about/about/>
#
# SPDX-License-Identifier: MIT

- type: stack
  parent: BaseMediumStack
  id: CableDet
  name: stack-explosive-cord
  icon: { sprite: "/Textures/Objects/Tools/cable-coils.rsi", state: coilex-30 }
  spawn: CableDetStack1
