# SPDX-FileCopyrightText: Space Station 14 Contributors <https://spacestation14.com/about/about/>
#
# SPDX-License-Identifier: MIT

blank_issues_enabled: true
contact_links:
  - name: Request a Feature
    url: https://discord.gg/rGvu9hKffJ
    about: Submit feature requests on our Discord server (https://discord.gg/rGvu9hKffJ).
