# SPDX-FileCopyrightText: Space Station 14 Contributors <https://spacestation14.com/about/about/>
#
# SPDX-License-Identifier: MIT

- type: chameleonOutfit
  id: SusChameleonOutfit
  loadoutName: chameleon-outfit-sus-name
  name: job-name-passenger
  icon: "JobIconPassenger"
  equipment:
    head: ClothingHeadHatBeret
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetGrey
    mask: ClothingMaskGas
    outerClothing: ClothingOuterVest
    jumpsuit: ClothingUniformJumpsuitColorBlack
    neck: ClothingNeckScarfStripedRed
    back: ClothingBackpack
    gloves: ClothingHandsGlovesColorBlack
    shoes: ClothingShoesColorBlack
    id: PassengerPDA
