# SPDX-FileCopyrightText: Space Station 14 Contributors <https://spacestation14.com/about/about/>
#
# SPDX-License-Identifier: MIT

name: "Labels: Untriaged"

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      if: join(github.event.issue.labels) == ''
      with:
        labels: "S: Untriaged"
