name: Publish

concurrency:
  group: publish
  cancel-in-progress: true

on:
  workflow_dispatch:
  # schedule:
   # - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fail if we are attempting to run on the master branch
      if: GITHUB.REF_NAME == 'workflow-test' && github.repository == 'Errant-4/space-station-14'
      run: exit 1

    - name: Main stuff
      run: echo 'Do the thing'

